### ISSUE TITLE
Smartlike.org: Add feeds - impossible to choose options for filters

### ISSUE THREAD

**Issue by gingerbread123** [vadim-frolov/thank-u#10]
when pressing "period" or "category" or other fields and choose one of the desired option (e.g. "video" in "category") - another option appears in the field ("blog"). This bug exists in all filters of this section.

**Comment by gingerbread123** [comment]
confirm

**Comment by gingerbread123** [comment]
After selecting the categories via the "add feed" filters, the name of feed doesnt fit the selected one

**Comment by gingerbread123** [comment]
now the name of feed is correct but the icon does not match it

**Comment by vadim-frolov** [comment]
please verify
