### ISSUE TITLE
Feeds: unlimited duplication of similar profiles, impossible to change existing profile 

### ISSUE THREAD

**Issue by gingerbread123** [vadim-frolov/thank-u#25]
You can many feeds with absolutely identical parameters. At the same time you cannot make changes to the filters of the existing feeds - just kill and make new one. 
Also there is no "trending" feed in the filter's list if you delete it occasionally (as I did))

**Comment by vadim-frolov** [comment]
freedom to duplicate is intended. "trending" is a sample. you are supposed to be able to remove it.

**Comment by gingerbread123** [comment]
- Is it possible to make notification like "such feed is already exists, would you like to make another one?"
- How about changes to existing feed? If a person wants to make minor change (e.g. change the music style) he will need to spend more time surfing throgh the filter list.
- I thought that trending is a sort of special algorithm which helps to see the trends. Sure a person should have right to kill it, but also to recover it

**Comment by vadim-frolov** [comment]
1. later?
2. select a feed, open "more" on the filter, edit, save under the same name
3. removed for now

**Comment by gingerbread123** [comment]
1.ok
2. not intuitive
3. ok

**Comment by gingerbread123** [comment]
in addition to item 2: 
a) "more" button is located quite far from the feed name. let's make the same appearance as at the content list (наводишь мышкой на контент - всплывают пиктограммы, в т.ч. edit)
b) when select the Lectures feed, open "more" on the filter and try to choose Genre by clicking the check box - impossible. You need to click the title of the genre to choose it.

**Comment by vadim-frolov** [comment]
> 2. You are right. What would be your wish design?
> 2.b - a separate bug, click on the genre instead please till it is fixed

**Comment by vadim-frolov** [comment]
good idea. to be implemented.

**Comment by vadim-frolov** [comment]
redesigned. can we close?

**Comment by gingerbread123** [comment]
yes
