### ISSUE TITLE
Left menu unavailable at the "about" page

### ISSUE THREAD

**Issue by gingerbread123** [vadim-frolov/thank-u#27]
when pressing the smartlike logo in the top left you go to the starting page ("about"). and the left-side menu is unavailable at this page - you should go to "content" or "creators" page to get it

**Comment by vadim-frolov** [comment]
intended behavior. left menu is to modify search from the top menu. why would you need left menu in about screen?

**Comment by gingerbread123** [comment]
1. When a visitor see a button on a page which couldn't be pressed impression appears that smth wrong with the site and it is not working properly
2. When a newcomer visits the site for the first time (or not yet fully understood all features) left menu will encourage him to look through the items and get more info. Especially taking into account that additional options like settings or links to more info are also in the left menu - more clicks are needed to find out details

**Comment by vadim-frolov** [comment]
1. what button?
2. left menu is generally a feed modifier - nothing to do with about.

**Comment by gingerbread123** [comment]
1. 
![image](https://user-images.githubusercontent.com/30407841/30879507-3e31ebec-a308-11e7-8bfc-82aab83aac17.png)
2.
![image](https://user-images.githubusercontent.com/30407841/30879559-67e60806-a308-11e7-84f0-554cc9cb3129.png)
